Document: testing-debian
Title: Debian testing-debian Manual
Author: <insert document author here>
Abstract: This manual describes what testing-debian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/testing-debian/testing-debian.sgml.gz

Format: postscript
Files: /usr/share/doc/testing-debian/testing-debian.ps.gz

Format: text
Files: /usr/share/doc/testing-debian/testing-debian.text.gz

Format: HTML
Index: /usr/share/doc/testing-debian/html/index.html
Files: /usr/share/doc/testing-debian/html/*.html
